
version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
