# Project build file

[build-system]
requires = ['setuptools', 'setuptools-scm>=8']
build-backend = 'setuptools.build_meta'
[tool.setuptools.packages.find]
where = ["src"]
[tool.setuptools_scm]

[project]
dynamic = ['version']

name = 'filefinder'
authors = [
    {name='Clément Haëck', email='clement.haeck@locean.ipsl.fr'}
]
description = 'Find files using a simple syntax.'

readme = 'README.md'
requires-python = '>=3.11'
classifiers = [
    'Development Status :: 4 - Beta',
    'License :: OSI Approved :: MIT License',

    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Operating System :: OS Independent',

    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Topic :: Utilities'
]

dependencies = [
]

[project.optional-dependencies]
dev = [
    'ruff',
    'mypy>=1.5',
]
docs = [
    'sphinx==9.1.*',
    'pydata-sphinx-theme==0.20.*',
]
tests = [
    'pytest>=7.4',
    'hypothesis',
    'coverage',
    'pytest-cov',
]

[project.urls]
'Source' = 'https://github.com/Descanonge/filefinder'
'Documentation' = 'https://filefinder.readthedocs.io'

[tool.mypy]
disable_error_code = ['annotation-unchecked']
# allow_untyped_defs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = 'py311'

[tool.ruff.lint]
extend-select = [
    'ANN',  # flake8-annotations
    'FBT',  # flake8-boolean-trap
    'B',    # flake8-bugbear
    'A',    # flake8-builtins
    'C4',   # flake8-comprehensions
    'FIX',  # flake8-fixme
    'ISC',  # flake8-implicit-str-concat
    'PIE',  # flake8-pie
    'Q',    # flake8-quotes
    'RET',  # flake8-return
    'SIM',  # flake8-simplify
    'ARG',  # flake8-unused-arguments
    'PTH',  # flake8-use-pathlib

    'I',    # isort
    'N',    # pep8-naming
    'E',    # pycodestyle Error
    'W',    # pycodestyle Warning
    'DOC',  # pydoclint
    'D',    # pydocstyle
    'F',    # Pyflakes
    'PL',   # Pylint
    'UP',   # pyupgrade
    'RUF',  # ruff
]

ignore = [
       'DTZ',  # datetime tz info
       'ANN401', # allow Any types
       'E226', # missing whitespace around arithmetic operator
       'D105', # missing docstring for magical method
       'D204', # one blank line after class
       'D213', # multiline docstring start at 2nd line
       'D417', # not all parameters need doc
       'PLR2004',  # magic values
       'SIM108', # ternary if operator
       'RET504', # assignement before return
       'BLE', # blind exceptions
]
unfixable = ["F401"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
"test_*" = ["FBT"]

[tool.ruff.lint.pycodestyle]
max-line-length = 90

[tool.ruff.lint.pydocstyle]
convention = 'numpy'

[tool.ruff.lint.pylint]
max-args = 9

[tool.ruff.format]
quote-style = 'double'
