"""Test group features."""

import re

import pytest
from hypothesis import given
from hypothesis import strategies as st
from lib import assert_fixed, assert_unfixed, form
from lib.format_generation import FormatSpecs, StFormat
from lib.group_generation import GroupSpecs, GroupValue, StGroup, examples

from filefinder.format import Format
from filefinder.group import Group, GroupParseError


def assert_grp(spec: str, expected_rgx: str, expected_fmt: str):
    grp = Group(spec, 0)
    assert grp.get_regex() == expected_rgx
    assert grp.fmt.fmt == expected_fmt


class TestGroupDefinition:
    @given(ref=StGroup.group())
    @examples.test
    def test_definition_parsing_hp(self, ref: GroupSpecs):
        """Test definitions generated by hypothesis."""
        g = Group(ref.definition, 0)

        assert g.name == ref.name
        assert str(g) == f"{ref.name}:0"

        assert g.optional == ref.opt

        if "rgx" in ref:
            assert g.rgx == ref.rgx

        if "fmt" in ref:
            assert g.fmt.fmt == ref.fmt

        if "bool_elts" in ref:
            a, b = ref.bool_elts
            assert g.options == (b, a)

        if "pre" in ref:
            assert g.prefix == ref.pre
        if "post" in ref:
            assert g.suffix == ref.post

        assert g.rgx == ref.get_regex()
        assert g.get_regex() == ref.get_regex(matching=True)

    def test_parse(self):
        """Test if a group can parse a value."""
        g = examples.get_group("fmt_int")
        assert g.parse("05") == 5
        g = examples.get_group("fmt_float")
        assert g.parse("0.5") == 0.5
        g = examples.get_group("fmt_str")
        assert g.parse("a.") == "a."

        g = examples.get_group("bool_basic")
        assert g.parse("a") is True
        assert g.parse("b") is False
        g = examples.get_group("bool_no_false")
        assert g.parse("a") is True
        assert g.parse("") is False

        g = examples.get_group("prefix_int")
        assert g.parse("_05") == 5
        g = examples.get_group("suffix_str")
        assert g.parse("a._") == "a."
        g = examples.get_group("prefix_opt")
        assert g.parse("_a.") == "a."

    @given(StGroup.group_value(parsable=True))
    def test_parse_hp(self, ref: GroupValue):
        """Test if a group can parse a value that it formatted."""
        grp = Group(ref.definition, 0)
        value_str = ref.get_value_str(ref.value)
        assert grp.parse(value_str) == ref.value

    @pytest.mark.parametrize(
        "spec",
        [
            # empty
            "",
            # no name
            ":fmt=08d",
            # argument given to flags
            "a:opt=stuff",
            "a:discard=stuff",
            # no argument given
            "a:fmt=",
            "a:pre=:opt",
            # missing properties
            "a",
            "a:pre=_",
            # properties specified twice
            "a:opt:fmt=02d:opt",
            "a:rgx=foo:rgx=bar",
            "a:opt:rgx=bar:opt:opt",
            # bad property
            "a:optional",
            "a:format=02d",
        ],
    )
    def test_bad_definition(self, spec: str):
        """Test some obvious bad definitions."""
        with pytest.raises(GroupParseError):
            Group(spec, 0)

    @pytest.mark.parametrize(
        "name,expected_rgx,expected_fmt",
        [
            ("Y", r"(\d{4})", "04d"),
            ("m", r"(\d\d)", "02d"),
            ("x", r"(\d{8})", "08d"),
            ("X", r"(\d{6})", "06d"),
            ("F", r"(\d{4}-\d\d-\d\d)", "s"),
        ],
    )
    def test_some_default_date_elements(self, name, expected_rgx, expected_fmt):
        """Test various default names."""
        assert_grp(name, expected_rgx, expected_fmt)

    def test_default_overwrite(self):
        """Test if rgx and fmt overwrite correctly the defaults."""
        assert_grp("Y:rgx=foo", "(foo)", "04d")
        assert_grp("Y:rgx=foo:fmt=s", "(foo)", "s")
        assert_grp("Y:rgx=foo:fmt=s:opt", "((?:foo)?)", "s")
        assert_grp("Y:fmt=08d", "({})".format(Format("08d").get_regex()), "08d")
        assert_grp("Y:bool=true:false:fmt=s", "(true|false)", "s")


class TestGroupFix:
    def test_fix(self) -> None:

        g = Group("foo:fmt=02d", 0)
        g.fix(1)
        assert_fixed(g, 1, "01", "01")

        g = Group("foo:fmt=.1f", 0)
        g.fix(0.5)
        assert_fixed(g, 0.5, "0.5", r"0\.5")

        g = Group("foo:fmt=s", 0)
        g.fix("a.")
        assert_fixed(g, "a.", "a.", "a.")

        g = Group("foo:bool=a.:b.", 0)
        g.fix(True)
        assert_fixed(g, True, "a.", r"a\.")

        g = Group("foo:fmt=02d:opt:pre=_", 0)
        g.fix(1)
        assert_fixed(g, 1, "_01", r"_01")
        g.fix(None)
        assert_fixed(g, None, "", "")

    @given(*StFormat.format_and_value(kind="dfeE"))
    def test_number_format(self, ref: FormatSpecs, number: float):
        fmt = ref.format_string
        g = Group(f"foo:fmt={fmt}", 0)
        g.fix(number)
        assert_fixed(g, number, form(fmt, number), re.escape(form(fmt, number)))
        g.unfix()
        assert_unfixed(g)

    @given(*StFormat.format_and_value(kind="s"))
    def test_s_format(self, ref: FormatSpecs, value: str):
        g = Group(f"foo:fmt={ref.format_string}", 0)
        g.fix(value)
        assert_fixed(g, value, value, value)
        assert g.get_regex() == f"({value})"

    def test_bool_value(self) -> None:
        g = Group("foo:bool=true.:false.", 0)
        g.fix(True)
        assert_fixed(g, True, "true.", r"true\.")
        g.fix(False)
        assert_fixed(g, False, "false.", r"false\.")

    @given(
        elements=st.lists(st.integers(), min_size=1),
        fmt=StFormat.format(kind="d").map(lambda ref: ref.format_string),
    )
    def test_integer_list(self, elements: list[int], fmt: str):
        g = Group(f"foo:fmt={fmt}", 0)
        g.fix(elements)
        formatted_elts = [form(fmt, e) for e in elements]
        assert_fixed(
            g,
            elements,
            formatted_elts,
            ("|".join(re.escape(e) for e in formatted_elts)),
        )

        with pytest.raises(ValueError):
            g.fix([])

    @given(a=st.integers(), b=st.integers())
    def test_unfix(self, a: int, b: int):
        g = Group("foo:fmt=d", 0)
        g.fix(a)
        assert g.fixed_value == a
        g.unfix()
        assert_unfixed(g)
        g.fix(b)
        assert g.fixed_value == b

    @given(a=st.integers(), b=st.integers())
    def test_consecutives_fix(self, a: int, b: int):
        g = Group("foo:fmt=d", 0)
        g.fix(a)
        assert g.fixed_value == a
        g.fix(b)
        assert g.fixed_value == b
