name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      HYPOTHESIS_PROFILE: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest pyfakefs hypothesis coverage pytest-cov

      - name: Install package
        run: |
          python -m pip install -e .

      - name: Cache Hypothesis database
        uses: actions/cache@v2
        id: cache-hypothesis
        with:
          path: .hypothesis
          key: ${{ runner.os }}-hypothesis
          restore-keys: |
            ${{ runner.os }}-hypothesis

      - name: Run tests
        run: python -m pytest -v --cov=filefinder --cov-report=xml tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Descanonge/filefinder
