name: Tests

on:
  push:
    branch: master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest pyfakefs hypothesis coverage pytest-cov

      - name: Install package
        run: |
          python -m pip install -e .

      - name: Run tests
        run: python -m pytest --cov=filefinder --cov-report=xml tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Descanonge/filefinder
